use crate::directed::{DirectedConfig, DirectedResult};
use crate::partition::PartitionResult;
use serde::{Deserialize, Serialize};

/// Test framework to generate enforcement tests for.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TestFramework {
    ArchUnit,
    CargoTest,
    Pytest,
    Generic,
}

/// Configuration for enforcement test generation.
#[derive(Debug, Clone)]
pub struct EnforcementConfig {
    pub framework: TestFramework,
    pub modules: DirectedConfig,
    pub strict: bool,
}

/// A generated test file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
    pub language: String,
}

/// Generate enforcement tests that lock in the desired architecture.
pub fn generate_enforcement_tests(
    config: &EnforcementConfig,
    directed: &DirectedResult,
    partition: &PartitionResult,
) -> Vec<GeneratedFile> {
    match config.framework {
        TestFramework::ArchUnit => generate_archunit(config, directed, partition),
        TestFramework::CargoTest => generate_cargo_test(config, directed, partition),
        TestFramework::Pytest => generate_pytest(config, directed, partition),
        TestFramework::Generic => generate_generic(config, directed, partition),
    }
}

fn generate_archunit(
    config: &EnforcementConfig,
    directed: &DirectedResult,
    partition: &PartitionResult,
) -> Vec<GeneratedFile> {
    let mut content = String::new();
    content.push_str("// Generated by frg dsm enforce\n");
    content.push_str("// Architecture defined in modules.toml\n\n");
    content.push_str("import com.tngtech.archunit.core.importer.ClassFileImporter;\n");
    content.push_str("import com.tngtech.archunit.junit.AnalyzeClasses;\n");
    content.push_str("import com.tngtech.archunit.junit.ArchTest;\n");
    content.push_str("import com.tngtech.archunit.lang.ArchRule;\n");
    content.push_str("import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.*;\n");
    content.push_str("import static com.tngtech.archunit.library.Architectures.*;\n\n");

    // Determine base package from module seeds
    let base_package = config
        .modules
        .modules
        .first()
        .and_then(|m| m.seeds.first())
        .map(|s| {
            let parts: Vec<&str> = s.split('.').collect();
            if parts.len() > 2 {
                parts[..2].join(".")
            } else {
                s.clone()
            }
        })
        .unwrap_or_else(|| "com.example".to_string());

    content.push_str(&format!(
        "@AnalyzeClasses(packages = \"{}\")\n",
        base_package
    ));
    content.push_str("class ModuleBoundaryTest {\n\n");

    // Generate module boundary rules
    for module in &directed.modules {
        let packages: String = module
            .current_members
            .iter()
            .map(|m| format!("            \"{}..\"", m))
            .collect::<Vec<_>>()
            .join(",\n");

        if packages.is_empty() {
            continue;
        }

        let var_name = module.name.replace(['-', ' '], "_");
        content.push_str(&format!(
            "    @ArchTest\n    static final ArchRule {}_module_boundary =\n",
            var_name
        ));
        content.push_str(&format!(
            "        classes().that().resideInAnyPackage(\n{}\n        )\n",
            packages
        ));

        if config.strict {
            content.push_str("        .should().onlyBeAccessed().byClassesThat()\n");
            content.push_str(&format!(
                "        .resideInAnyPackage(\n{}\n        );\n\n",
                packages
            ));
        } else {
            content.push_str("        .should().onlyHaveDependentClassesThat()\n");
            content.push_str(&format!(
                "        .resideInAnyPackage(\n{}\n        );\n\n",
                packages
            ));
        }
    }

    // No-cycles rule
    content.push_str("    @ArchTest\n");
    content.push_str("    static final ArchRule no_cycles_between_modules =\n");
    content.push_str(&format!(
        "        slices().matching(\"{}.(*)..\")\n",
        base_package
    ));
    content.push_str("        .should().beFreeOfCycles();\n\n");

    // Layer rule from partition
    if partition.layers.len() >= 2 {
        content.push_str("    @ArchTest\n");
        content.push_str("    static final ArchRule layer_dependencies_respected =\n");
        content.push_str("        layeredArchitecture()\n");
        content.push_str("            .consideringAllDependencies()\n");

        for (layer, name) in partition.layers.iter().zip(&partition.layer_names) {
            let _ = layer; // layer indices reference original matrix
            content.push_str(&format!(
                "            .layer(\"{}\").definedBy(\"..{}..\") // auto-detected\n",
                name,
                name.to_lowercase().replace(' ', "")
            ));
        }

        content.push_str("            ;\n\n");
    }

    content.push_str("}\n");

    vec![GeneratedFile {
        path: "src/test/java/arch/ModuleBoundaryTest.java".to_string(),
        content,
        language: "java".to_string(),
    }]
}

fn generate_cargo_test(
    _config: &EnforcementConfig,
    directed: &DirectedResult,
    _partition: &PartitionResult,
) -> Vec<GeneratedFile> {
    let mut content = String::new();
    content.push_str("// Generated by frg dsm enforce\n");
    content.push_str("#[cfg(test)]\n");
    content.push_str("mod architecture_tests {\n");
    content.push_str("    use std::process::Command;\n\n");

    for module in &directed.modules {
        for other in &directed.modules {
            if module.name == other.name {
                continue;
            }
            // Check that module doesn't depend on other (unless allowed)
            let has_dep = module
                .boundary_deps
                .iter()
                .any(|d| d.to_module == other.name);
            if !has_dep {
                let test_name = format!(
                    "{}_does_not_depend_on_{}",
                    module.name.replace('-', "_"),
                    other.name.replace('-', "_")
                );
                content.push_str(&format!("    #[test]\n    fn {}() {{\n", test_name));
                content.push_str(&format!(
                    "        let output = Command::new(\"grep\")\n            .args([\"-r\", \"use crate::{}\", \"src/{}/\"])\n            .output().unwrap();\n",
                    other.name, module.name
                ));
                content.push_str(&format!(
                    "        assert!(output.stdout.is_empty(),\n            \"{} should not depend on {}\");\n",
                    module.name, other.name
                ));
                content.push_str("    }\n\n");
            }
        }
    }

    content.push_str("}\n");

    vec![GeneratedFile {
        path: "tests/architecture_test.rs".to_string(),
        content,
        language: "rust".to_string(),
    }]
}

fn generate_pytest(
    _config: &EnforcementConfig,
    directed: &DirectedResult,
    _partition: &PartitionResult,
) -> Vec<GeneratedFile> {
    let mut content = String::new();
    content.push_str("# Generated by frg dsm enforce\n");
    content.push_str("import ast\nimport os\nimport pytest\n\n");
    content.push_str("def get_imports(filepath):\n");
    content.push_str("    \"\"\"Extract import statements from a Python file.\"\"\"\n");
    content.push_str("    with open(filepath) as f:\n");
    content.push_str("        tree = ast.parse(f.read())\n");
    content.push_str("    imports = []\n");
    content.push_str("    for node in ast.walk(tree):\n");
    content.push_str("        if isinstance(node, ast.Import):\n");
    content.push_str("            for alias in node.names:\n");
    content.push_str("                imports.append(alias.name)\n");
    content.push_str("        elif isinstance(node, ast.ImportFrom) and node.module:\n");
    content.push_str("            imports.append(node.module)\n");
    content.push_str("    return imports\n\n");

    for module in &directed.modules {
        for other in &directed.modules {
            if module.name == other.name {
                continue;
            }
            let has_dep = module
                .boundary_deps
                .iter()
                .any(|d| d.to_module == other.name);
            if !has_dep {
                content.push_str(&format!(
                    "def test_{}_does_not_import_{}():\n",
                    module.name.replace('-', "_"),
                    other.name.replace('-', "_")
                ));
                content.push_str(&format!(
                    "    \"\"\"Module '{}' should not depend on '{}'.\"\"\"\n",
                    module.name, other.name
                ));
                content.push_str(&format!(
                    "    module_dir = os.path.join('src', '{}')\n",
                    module.name
                ));
                content.push_str("    if not os.path.exists(module_dir):\n");
                content.push_str("        pytest.skip('Module directory not found')\n");
                content.push_str("    violations = []\n");
                content.push_str("    for root, _, files in os.walk(module_dir):\n");
                content.push_str("        for f in files:\n");
                content.push_str("            if f.endswith('.py'):\n");
                content.push_str("                path = os.path.join(root, f)\n");
                content.push_str("                for imp in get_imports(path):\n");
                content.push_str(&format!(
                    "                    if imp.startswith('{}'):\n",
                    other.name
                ));
                content.push_str("                        violations.append(f'{path}: {imp}')\n");
                content.push_str(&format!(
                    "    assert not violations, f\"{} should not import {}: {{violations}}\"\n\n",
                    module.name, other.name
                ));
            }
        }
    }

    vec![GeneratedFile {
        path: "tests/test_architecture.py".to_string(),
        content,
        language: "python".to_string(),
    }]
}

fn generate_generic(
    _config: &EnforcementConfig,
    directed: &DirectedResult,
    _partition: &PartitionResult,
) -> Vec<GeneratedFile> {
    let mut content = String::new();
    content.push_str("#!/bin/bash\n");
    content.push_str("# Generated by frg dsm enforce\n");
    content.push_str("# Architecture boundary enforcement tests\n\n");
    content.push_str("FAILED=0\n\n");

    for module in &directed.modules {
        for other in &directed.modules {
            if module.name == other.name {
                continue;
            }
            let has_dep = module
                .boundary_deps
                .iter()
                .any(|d| d.to_module == other.name);
            if !has_dep {
                content.push_str(&format!(
                    "# {} should not depend on {}\n",
                    module.name, other.name
                ));
                content.push_str(&format!(
                    "if grep -r \"{}\" src/{} 2>/dev/null | grep -v test; then\n",
                    other.name, module.name
                ));
                content.push_str(&format!(
                    "    echo \"FAIL: {} depends on {}\"\n",
                    module.name, other.name
                ));
                content.push_str("    FAILED=$((FAILED + 1))\nfi\n\n");
            }
        }
    }

    content.push_str("if [ $FAILED -eq 0 ]; then\n");
    content.push_str("    echo \"All architecture boundary checks passed\"\nelse\n");
    content.push_str("    echo \"$FAILED architecture boundary violations found\"\n");
    content.push_str("    exit 1\nfi\n");

    vec![GeneratedFile {
        path: "tests/check_architecture.sh".to_string(),
        content,
        language: "bash".to_string(),
    }]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cycles::find_cycles;
    use crate::directed::{directed_analysis, DirectedConfig, ModuleSpec};
    use crate::extract::{Edge, EdgeKind};
    use crate::matrix::DsmMatrix;
    use crate::partition::partition;

    fn make_edge(src: &str, tgt: &str) -> Edge {
        Edge {
            source: src.to_string(),
            target: tgt.to_string(),
            weight: 1.0,
            kind: EdgeKind::Import,
            cross_language: None,
        }
    }

    fn sample_directed() -> (DsmMatrix, DirectedResult, PartitionResult) {
        let edges = vec![
            make_edge("db.core", "db.io"),
            make_edge("svc.main", "db.core"),
            make_edge("cql.parser", "svc.main"),
        ];
        let m = DsmMatrix::from_edges(&edges);
        let ci = find_cycles(&m);
        let config = DirectedConfig {
            modules: vec![
                ModuleSpec {
                    name: "storage".to_string(),
                    description: "".to_string(),
                    seeds: vec!["db".to_string()],
                    include: vec![],
                    exclude: vec![],
                },
                ModuleSpec {
                    name: "service".to_string(),
                    description: "".to_string(),
                    seeds: vec!["svc".to_string()],
                    include: vec![],
                    exclude: vec![],
                },
                ModuleSpec {
                    name: "query".to_string(),
                    description: "".to_string(),
                    seeds: vec!["cql".to_string()],
                    include: vec![],
                    exclude: vec![],
                },
            ],
        };
        let dir = directed_analysis(&m, &config, &ci);
        let part = partition(&m);
        (m, dir, part)
    }

    #[test]
    fn archunit_generates_valid_java() {
        let (_, dir, part) = sample_directed();
        let config = EnforcementConfig {
            framework: TestFramework::ArchUnit,
            modules: DirectedConfig {
                modules: vec![ModuleSpec {
                    name: "storage".to_string(),
                    description: "".to_string(),
                    seeds: vec!["db".to_string()],
                    include: vec![],
                    exclude: vec![],
                }],
            },
            strict: false,
        };
        let files = generate_enforcement_tests(&config, &dir, &part);
        assert_eq!(files.len(), 1);
        assert!(files[0].content.contains("ArchTest"));
        assert_eq!(files[0].language, "java");
    }

    #[test]
    fn cargo_test_generates_valid_rust() {
        let (_, dir, part) = sample_directed();
        let config = EnforcementConfig {
            framework: TestFramework::CargoTest,
            modules: DirectedConfig { modules: vec![] },
            strict: false,
        };
        let files = generate_enforcement_tests(&config, &dir, &part);
        assert_eq!(files.len(), 1);
        assert!(files[0].content.contains("#[cfg(test)]"));
        assert_eq!(files[0].language, "rust");
    }

    #[test]
    fn pytest_generates_valid_python() {
        let (_, dir, part) = sample_directed();
        let config = EnforcementConfig {
            framework: TestFramework::Pytest,
            modules: DirectedConfig { modules: vec![] },
            strict: false,
        };
        let files = generate_enforcement_tests(&config, &dir, &part);
        assert_eq!(files.len(), 1);
        assert!(files[0].content.contains("import pytest"));
        assert_eq!(files[0].language, "python");
    }

    #[test]
    fn generic_generates_shell_script() {
        let (_, dir, part) = sample_directed();
        let config = EnforcementConfig {
            framework: TestFramework::Generic,
            modules: DirectedConfig { modules: vec![] },
            strict: false,
        };
        let files = generate_enforcement_tests(&config, &dir, &part);
        assert_eq!(files.len(), 1);
        assert!(files[0].content.contains("#!/bin/bash"));
        assert_eq!(files[0].language, "bash");
    }
}
